---
- name: Configurar direccionamiento IPv6 en Loopback 44
  hosts: routers
  gather_facts: no
  tasks:
    - name: Aplicar configuraciones de IPv6 en Loopback 44
      ios_config:
        lines:
          - description Loopback 44 - Creada mediante Ansible
          - ipv6 address 3001:ABCD:ABCD:4::4/128
          - ipv6 address FE80::1 link-local
        parents: interface Loopback44
